### PR TITLE
Update on the travel front (boston)

### PR DESCRIPTION
**Pull request by wassemgtk**
Logan airport in Boston is complying with a court order

### CODE REVIEW

**Comment by wassemgtk** [comment]
@irishbryan please review and approve!

**Comment by irishbryan** [comment]
Thanks for content @wassemgtk, will defer to @aymannadeem here. This particular content feels more like a news update to me than an immigration resource , wonder if we should wait until YourHaq has a proper home for these types of updates?

**Comment by wassemgtk** [comment]
@irishbryan I hear you. @aymannadeem I see you this as an important update for everyone trying to comeback. but still up to you guys :)

**Comment by aymannadeem** [comment]
@wassemgtk—thanks for ensuring important information is being surfaced! 

I agree that it's a vital piece of information for those traveling, but is more news to be aware of instead of a legal resource/lawyer they could contact to find aid. Do you know any law firm looking at this case in particular, localized to the Boston area perhaps? I'd love to add lawyers who are looking at helping those affected by this specifically, and linking to that.

**Comment by aymannadeem** [comment]
@wassemgtk—to clarify, if anyone gets to Logan airport and is denied boarding despite the court order, who do they contact?

**Comment by wassemgtk** [comment]
They aren't being allowed to board abroad. When they get to Logan airport, they can enter.

**Comment by aymannadeem** [comment]
Thanks for this @waseem! Closing at the moment since this content is stale now.

**Pull request closed without merging**
